"""Paper-ready LaTeX tables for the main study, driven entirely from the on-disk
analysis JSONs (no hardcoded metrics). Each emitted file is a complete float that
the paper imports via \\input{generated/...}; existing \\label keys are preserved
so cross-references keep resolving after the inline tables are swapped out.

Outputs into code/outputs/main_study/export/ (the staging dir promoted to
thesis-msc/generated/ by make export-assets):
  mainstudy_cost.tex         -> tab:results-cost-quality (deployment cost, both cards)
  mainstudy_cost_decomposition.tex -> tab:results-cost-decomp (build/answer x LLM/embed)
  mainstudy_breakeven.tex    -> tab:results-breakeven    (break-even n* per document)
(mainstudy_significance.tex is owned by significance_main_study.py, which emits the
Holm-adjusted six-pair table; this script no longer writes it.)
The three figure PDFs/PNGs are also copied in with stable paper names.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MS = ROOT / "outputs" / "main_study"
EXPORT = MS / "export"
EXPORT.mkdir(parents=True, exist_ok=True)

ARCHS = ["flat", "naive_rag", "raptor", "graphrag"]
LABEL = {"flat": "Flat", "naive_rag": "Naive RAG", "raptor": "RAPTOR", "graphrag": "GraphRAG"}

sig = json.loads((MS / "significance.json").read_text(encoding="utf-8"))
cost = json.loads((MS / "cost_per_arch.json").read_text(encoding="utf-8"))
brk = json.loads((MS / "breakeven.json").read_text(encoding="utf-8"))
brk_ds = json.loads((MS / "breakeven_by_dataset.json").read_text(encoding="utf-8"))
costds = json.loads((MS / "cost_by_dataset.json").read_text(encoding="utf-8"))
mem = json.loads((MS / "memorization_control.json").read_text(encoding="utf-8"))

QA = sig["datasets"]["qasper"]["per_arch"]
NV = sig["datasets"]["novelqa"]["per_arch"]
PC = cost["per_arch"]

# The main-study run directory (predictions + call ledger), for the few macros
# whose values are measured per-call rather than pre-aggregated in the JSONs.
RUN = sorted((ROOT / "outputs" / "runs").glob("main-full-*"))[0]


def ci(d: dict) -> str:
    return f"{d['mean']:.3f} [{d['ci_low']:.3f}, {d['ci_high']:.3f}]"


HEADER = "% Auto-generated by code/scripts/tables_main_study.py from\n" \
         "% code/outputs/main_study/{significance,cost_per_arch,cost_by_dataset,breakeven,breakeven_by_dataset,memorization_control}.json\n" \
         "% Do not edit by hand; regenerate and re-export.\n"


def write(name: str, body: str) -> None:
    (EXPORT / name).write_text(HEADER + body, encoding="utf-8")
    print(f"  wrote {name}")


def texint(n: int) -> str:
    """Integer with a LaTeX-math thousands separator, e.g. 1348 -> 1{,}348."""
    return f"{n:,}".replace(",", "{,}")


def cost_table() -> None:
    def rows(ds):
        out = []
        for a in ARCHS:  # canonical order: Flat, Naive RAG, RAPTOR, GraphRAG
            c = costds[f"base|{a}|{ds}"]
            out.append(f"{LABEL[a]} & {c['c_off_total']:.2f} & {c['c_on_total']:.2f} & "
                       f"{c['total']:.2f} & {c['c_on_per_query']*1000:.2f} \\\\")
        return "\n".join(out)

    qd = brk_ds["base|raptor|qasper"]["density"]
    nd = brk_ds["base|raptor|novelqa"]["density"]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Per-architecture deployment cost in USD, computed \emph{{within each dataset}}
(standard card): the one-time build cost (the per-document $C_{{\text{{build}}}}$ summed
over the dataset's documents), the answering cost summed over its queries, their sum
(Total)---the total deployment spend, i.e.\ the numerator of
$\bar{{C}}_{{\text{{deploy}}}}$ before amortizing over the query count---and the
marginal per-query answering cost $C_{{\text{{query}}}}$
(m\$, $10^{{-3}}$~USD).}}\label{{tab:results-cost-quality}}
\begin{{tabular}}{{lrrrr}}
\toprule
 & Build & Answer & Total & $C_{{\text{{query}}}}$ \\
Architecture & (USD) & (USD) & (USD) & (m\$) \\
\midrule
\multicolumn{{5}}{{l}}{{\textit{{QASPER}} ($\approx{qd:.0f}$ questions/paper)}} \\
{rows('qasper')}
\midrule
\multicolumn{{5}}{{l}}{{\textit{{NovelQA}} ($\approx{nd:.0f}$ questions/novel)}} \\
{rows('novelqa')}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_cost.tex", body)


def flat_cached_split() -> tuple[float, float]:
    """Split Flat's standard-card answering total into the cached re-reads and the
    undiscounted remainder. The cache-discount card prices cached input at 0.1x
    uncached vs the standard card's 0.25x (a 0.4x factor), so the standard-to-
    discount saving is 0.6x of the cached re-read cost; invert it to recover the
    cached re-reads under the standard card and the undiscounted remainder
    (uncached first read of each document plus all output)."""
    f_base, f_cache = PC["base|flat"]["total"], PC["cache|flat"]["total"]
    cached_base = (f_base - f_cache) / 0.6
    return cached_base, f_base - cached_base


def cost_decomposition_table() -> None:
    # Where each architecture's deployment dollars actually go: the one-time build
    # vs the answering, each split into LLM API calls and local BGE-M3 embedding.
    # Standard card; a study-wide roll-up (summed over both datasets --- the
    # per-dataset split is in cost_table). Driven from cost_per_arch.json.
    rows = []
    for a in ARCHS:  # canonical order: Flat, Naive RAG, RAPTOR, GraphRAG
        b = PC[f"base|{a}"]
        rows.append(
            f"{LABEL[a]} & {b['gemini_off']:.2f} & {b['embed_off']:.2f} & "
            f"{b['gemini_on']:.2f} & {b['embed_on']:.2f} & {b['total']:.2f} & "
            f"{b['c_store_total']:.3f} \\\\")
    rows_tex = "\n".join(rows)
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Where each architecture's deployment dollars go, summed over the whole study
(standard card; the per-dataset split is Table~\ref{{tab:results-cost-quality}}): the
one-time build cost (the per-document $C_{{\text{{build}}}}$ summed over all documents)
and the answering cost (the per-query $C_{{\text{{query}}}}$ summed over all queries),
each split into LLM API calls and local BGE-M3 embedding. Persistent-artifact storage
($C_{{\text{{store}}}}$) is shown separately and is excluded from the deployment
totals. All values in USD.}}\label{{tab:results-cost-decomp}}
\begin{{tabular}}{{lrrrrrr}}
\toprule
 & \multicolumn{{2}}{{c}}{{Build}} & \multicolumn{{2}}{{c}}{{Answer}} & & \\
\cmidrule(lr){{2-3}}\cmidrule(lr){{4-5}}
Architecture & LLM & embed & LLM & embed & Total & Storage \\
 & (USD) & (USD) & (USD) & (USD) & (USD) & (USD) \\
\midrule
{rows_tex}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_cost_decomposition.tex", body)


def breakeven_table() -> None:
    def fmt_nstar(b):
        n = b["n_star"]
        if n is None:
            return "never"
        return "any $n\\ge1$" if n < 1 else f"{n:.1f}"

    def rows(ds):
        out = []
        for a in ("naive_rag", "raptor", "graphrag"):
            bb, bc = brk_ds[f"base|{a}|{ds}"], brk_ds[f"cache|{a}|{ds}"]
            out.append(f"{LABEL[a]} & {bb['c_off_per_doc']*1000:.2f} & {bb['c_on_per_query']*1000:.3f} "
                       f"& {fmt_nstar(bb)} & {fmt_nstar(bc)} \\\\")
        return "\n".join(out)

    def flatq(ds, card):
        return brk_ds[f"{card}|raptor|{ds}"]["flat_c_on_per_query"] * 1000

    qd = brk_ds["base|raptor|qasper"]["density"]
    nd = brk_ds["base|raptor|novelqa"]["density"]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Break-even density versus cache-aware Flat, computed \emph{{within each
dataset}}. An architecture's one-time per-document build cost $C_{{\text{{build}}}}$
amortizes over $n$ questions per document; the two $n^\star$ columns give the
break-even density (Section~\ref{{sec:eval-protocol}}) under the
standard card and the cache-discount card.}}\label{{tab:results-breakeven}}
\begin{{tabular}}{{lrrcc}}
\toprule
 & $C_{{\text{{build}}}}$ & $C_{{\text{{query}}}}$ & $n^\star$ & $n^\star$ \\
Architecture & (m\$) & (m\$) & standard card & cache-discount card \\
\midrule
\multicolumn{{5}}{{l}}{{\textit{{QASPER}} ($\approx{qd:.0f}$ questions/paper; Flat {flatq('qasper','base'):.2f}/{flatq('qasper','cache'):.2f}~m\$/q standard/cache-discount)}} \\
{rows('qasper')}
\midrule
\multicolumn{{5}}{{l}}{{\textit{{NovelQA}} ($\approx{nd:.0f}$ questions/novel; Flat {flatq('novelqa','base'):.2f}/{flatq('novelqa','cache'):.2f}~m\$/q standard/cache-discount)}} \\
{rows('novelqa')}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_breakeven.tex", body)


def memorization_table() -> None:
    """Per-architecture quality vs the closed-book floor, both datasets."""
    nv, qa = mem["novelqa"], mem["qasper"]
    nv_floor, qa_floor = nv["closed_book"], qa["closed_book"]
    rows = [f"Closed-book floor & {qa_floor:.2f} & --- & {nv_floor:.2f} & --- \\\\", r"\midrule"]
    for a in ARCHS:
        n, q = nv["per_arch"][a], qa["per_arch"][a]
        rows.append(f"{LABEL[a]} & {q['answer_f1']:.2f} & {q['lift']:+.2f} & "
                    f"{n['accuracy']:.2f} & {n['lift']:+.2f} \\\\")
    rows_tex = "\n".join(rows)
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Closed-book control: per-architecture answer quality against the closed-book
floor (the same questions asked with the document withheld; Section~\ref{{sec:eval-protocol}}). The lift column is the with-document score minus the closed-book
floor.}}\label{{tab:results-memorization}}
\begin{{tabular}}{{lcccc}}
\toprule
 & \multicolumn{{2}}{{c}}{{QASPER Answer-F1}} & \multicolumn{{2}}{{c}}{{NovelQA accuracy}} \\
Architecture & with doc. & lift & with doc. & lift \\
\midrule
{rows_tex}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_memorization.tex", body)


def _iter_jsonl(path: Path):
    """Yield dict rows from a JSONL/concatenated-JSON file robustly (same
    tolerance as breakeven_main_study.iter_ledger)."""
    dec = json.JSONDecoder()
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            s, pos = raw.strip(), 0
            while pos < len(s):
                while pos < len(s) and s[pos].isspace():
                    pos += 1
                if pos >= len(s):
                    break
                try:
                    o, pos = dec.raw_decode(s, pos)
                except json.JSONDecodeError:
                    break
                if isinstance(o, dict):
                    yield o


def doc_token_means() -> dict[str, float]:
    """Mean full-document context length per dataset (Gemini tokens), measured
    over the scored (post-exclusion) cohort: each document's full-context read
    by the flat architecture, recovered from the run ledger with the same
    attribution breakeven_main_study.py uses for doc_tokens (ledger rows map to
    predictions in execution order; per document, the max uncached input tokens
    over its run-index-0 generate rows). Cross-check: the NovelQA mean agrees
    with bookmeta.json's per-novel tokenlen over the same 55 novels to within
    ~2% (tokenizer difference)."""
    scored = {"qasper": set(), "novelqa": set()}
    for o in _iter_jsonl(MS / "scored_cells.jsonl"):
        scored[o["dataset"]].add(o["cluster"])
    order = [(o["dataset"], o["paper_id"])
             for o in _iter_jsonl(RUN / "flat_predictions.jsonl")
             if o.get("run_index") == 0]
    dec = json.JSONDecoder()
    toks: dict[tuple[str, str], int] = {}
    i = 0
    with open(RUN / "ledger.jsonl", encoding="utf-8") as fh:
        for raw in fh:
            # cheap substring pre-filter only; the exact fields are re-checked
            # on the parsed object below (a flat/generate row always contains
            # both quoted values, so no qualifying row can be skipped).
            if '"flat"' not in raw or '"generate"' not in raw:
                continue
            s, pos = raw.strip(), 0
            while pos < len(s):
                while pos < len(s) and s[pos].isspace():
                    pos += 1
                if pos >= len(s):
                    break
                try:
                    o, pos = dec.raw_decode(s, pos)
                except json.JSONDecodeError:
                    break
                if not (isinstance(o, dict) and o.get("architecture") == "flat"
                        and o.get("stage") == "generate" and o.get("run_index") == 0):
                    continue
                ds, pid = order[i]
                i += 1
                if pid in scored[ds]:
                    toks[(ds, pid)] = max(toks.get((ds, pid), 0),
                                          o.get("uncached_input_tokens", 0) or 0)
    if i != len(order):
        raise RuntimeError(f"ledger vs predictions row mismatch: {i} != {len(order)}")
    means: dict[str, float] = {}
    for ds in ("qasper", "novelqa"):
        v = [t for (d, _), t in toks.items() if d == ds]
        means[ds] = sum(v) / len(v)
    return means


def repeat_identity_min_novel() -> float:
    """Minimum across architectures of the NovelQA repeat-identity rate: the
    percentage of answered NovelQA questions whose five T=0 repeats parse to
    the same option letter (predicted_letter, the scoring parse). This is the
    determinism check that lets run-index-0 stand in for all five repeats in
    scored_cells (see build_scored_cells.py)."""
    worst = 100.0
    for a in ARCHS:
        letters: dict[tuple[str, str], dict[int, object]] = {}
        for o in _iter_jsonl(RUN / f"{a}_predictions.jsonl"):
            if o.get("dataset") != "novelqa":
                continue
            letters.setdefault((o["paper_id"], o["question_id"]), {})[
                o["run_index"]] = o.get("predicted_letter")
        full = [v for v in letters.values() if len(v) == 5]
        pct = 100.0 * sum(1 for v in full if len(set(v.values())) == 1) / len(full)
        worst = min(worst, pct)
    return worst


def macros() -> None:
    """Inline result numbers as \\input-able \\newcommand macros, so values can stay in
    the prose while still living in exactly one regenerated place (no hand-typed metrics).
    Driven from the same JSONs as the tables, plus the run ledger for the measured
    document-length and repeat-identity macros. LaTeX control sequences are letters-only,
    so e.g. Answer-F1 -> \\qFlatFone."""
    def fp(ds: str, a: str, b: str) -> dict:
        return next(p for p in sig["datasets"][ds]["pairwise"]
                    if {p["a"], p["b"]} == {a, b})
    fn = fp("qasper", "flat", "naive_rag")
    nr = fp("novelqa", "naive_rag", "raptor")
    dt = doc_token_means()

    def storage_pct(a: str) -> str:
        # storage share of the architecture's study-wide cost, in percent
        # (two significant figures); prose appends \% itself.
        b = PC[f"base|{a}"]
        return f"{100 * b['c_store_total'] / (b['total'] + b['c_store_total']):.2g}"

    m = [
        f"\\newcommand{{\\qFlatFone}}{{{QA['flat']['mean']:.3f}}}",
        f"\\newcommand{{\\qNaiveFone}}{{{QA['naive_rag']['mean']:.3f}}}",
        f"\\newcommand{{\\qRaptorFone}}{{{QA['raptor']['mean']:.3f}}}",
        f"\\newcommand{{\\qGraphFone}}{{{QA['graphrag']['mean']:.3f}}}",
        f"\\newcommand{{\\nFlatAcc}}{{{NV['flat']['mean']:.3f}}}",
        f"\\newcommand{{\\nNaiveAcc}}{{{NV['naive_rag']['mean']:.3f}}}",
        f"\\newcommand{{\\nRaptorAcc}}{{{NV['raptor']['mean']:.3f}}}",
        f"\\newcommand{{\\nGraphAcc}}{{{NV['graphrag']['mean']:.3f}}}",
        f"\\newcommand{{\\deltaFlatNaiveQ}}{{{fn['mean_diff']:.3f}}}",
        f"\\newcommand{{\\pFlatNaiveQ}}{{{fn['p_value']:.3f}}}",
        f"\\newcommand{{\\deltaNaiveRaptorN}}{{{nr['mean_diff']:.3f}}}",
        f"\\newcommand{{\\costFlatQ}}{{{costds['base|flat|qasper']['total']:.2f}}}",
        f"\\newcommand{{\\costRaptorQ}}{{{costds['base|raptor|qasper']['total']:.2f}}}",
        f"\\newcommand{{\\costFlatN}}{{{costds['base|flat|novelqa']['total']:.2f}}}",
        f"\\newcommand{{\\costRaptorN}}{{{costds['base|raptor|novelqa']['total']:.2f}}}",
        # study-wide deployment totals under the two price cards
        f"\\newcommand{{\\studyTotalStandardCard}}{{{cost['deployment_total']['base']:.2f}}}",
        f"\\newcommand{{\\studyTotalCacheDiscountCard}}{{{cost['deployment_total']['cache']:.2f}}}",
        # Flat's standard-card answering total, split into the cached re-reads
        # (the part the cache-discount card reprices) and the undiscounted
        # remainder (uncached first read of each document plus all output); see
        # flat_cached_split() for the inversion.
        f"\\newcommand{{\\flatCachedReReads}}{{{flat_cached_split()[0]:.2f}}}",
        f"\\newcommand{{\\flatUncachedFirstRead}}{{{flat_cached_split()[1]:.2f}}}",
        f"\\newcommand{{\\nstarRaptorQ}}{{{round(brk_ds['base|raptor|qasper']['n_star'])}}}",
        f"\\newcommand{{\\nstarRaptorN}}{{{round(brk_ds['base|raptor|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\nstarRaptorNcache}}{{{round(brk_ds['cache|raptor|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\nstarGraphN}}{{{round(brk_ds['base|graphrag|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\nstarGraphNcache}}{{{round(brk_ds['cache|graphrag|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\densQasper}}{{{round(brk_ds['base|raptor|qasper']['density'])}}}",
        f"\\newcommand{{\\densNovel}}{{{round(brk_ds['base|raptor|novelqa']['density'])}}}",
        f"\\newcommand{{\\memQasperFloor}}{{{mem['qasper']['closed_book']:.2f}}}",
        f"\\newcommand{{\\memNovelFloor}}{{{mem['novelqa']['closed_book']:.2f}}}",
        f"\\newcommand{{\\memFlatLiftN}}{{{mem['novelqa']['per_arch']['flat']['lift']:+.2f}}}",
        f"\\newcommand{{\\memGraphLiftN}}{{{mem['novelqa']['per_arch']['graphrag']['lift']:+.2f}}}",
        f"\\newcommand{{\\memFlatLiftQ}}{{{mem['qasper']['per_arch']['flat']['lift']:+.2f}}}",
        f"\\newcommand{{\\memGraphLiftQ}}{{{mem['qasper']['per_arch']['graphrag']['lift']:+.2f}}}",
        f"\\newcommand{{\\billedGemini}}{{{cost['billed_gemini']:.2f}}}",
        f"\\newcommand{{\\nNovelScored}}{{{texint(NV['flat']['n_questions'])}}}",
        f"\\newcommand{{\\nNovelDocs}}{{{NV['flat']['n_clusters']}}}",
        f"\\newcommand{{\\nQasperQ}}{{{texint(QA['flat']['n_questions'])}}}",
        f"\\newcommand{{\\nQasperDocs}}{{{QA['flat']['n_clusters']}}}",
        f"\\newcommand{{\\nTotalQ}}{{{texint(QA['flat']['n_questions'] + NV['flat']['n_questions'])}}}",
        f"\\newcommand{{\\nTotalDocs}}{{{cost['n_docs']}}}",
        # measured document lengths (ledger full-context reads, scored cohort):
        # NovelQA mean in kilotokens to the nearest 10, QASPER to the nearest 1.
        # The ratio derives from the displayed rounded values so the three
        # numbers stay arithmetically consistent on the page.
        f"\\newcommand{{\\docTokensNovelK}}{{{round(dt['novelqa'] / 10000) * 10}}}",
        f"\\newcommand{{\\docTokensQasperK}}{{{round(dt['qasper'] / 1000)}}}",
        f"\\newcommand{{\\docLenRatio}}{{{round((round(dt['novelqa'] / 10000) * 10) / round(dt['qasper'] / 1000))}}}",
        f"\\newcommand{{\\repeatIdentityMinN}}{{{repeat_identity_min_novel():.1f}}}",
        # QASPER analogue of the identity rate: worst-architecture mean
        # within-question SD of Answer-F1 across the five repeats.
        f"\\newcommand{{\\qasperRepeatSdMax}}{{{json.loads((MS / 'repeat_spread.json').read_text(encoding='utf-8'))['qasper_max_arch_sd']:.3f}}}",
        f"\\newcommand{{\\storagePctFlat}}{{{storage_pct('flat')}}}",
        f"\\newcommand{{\\storagePctNaive}}{{{storage_pct('naive_rag')}}}",
        f"\\newcommand{{\\storagePctRaptor}}{{{storage_pct('raptor')}}}",
        f"\\newcommand{{\\storagePctGraph}}{{{storage_pct('graphrag')}}}",
    ]
    write("mainstudy_macros.tex", "\n".join(m) + "\n")


def tau_table() -> None:
    """Pilot rank-stability distribution table (tab:results-tau), generated from the
    under-gold cross-dataset pairwise blocks and the permutation-test stats, so the lone
    remaining hand-typed results table joins the generated-asset pipeline."""
    SAN = ROOT / "outputs" / "sanity"
    cd = json.loads((SAN / "kendall_cross_dataset_under_gold_20260520.json").read_text(encoding="utf-8"))
    ks = json.loads((SAN / "kendall_stats_20260520.json").read_text(encoding="utf-8"))["results"]

    def sci(p: float) -> str:
        from math import log10, floor
        e = floor(log10(p))
        m = round(p / 10 ** e)
        return f"\\({m}\\!\\times\\!10^{{{e}}}\\)"

    def col(view: str) -> dict:
        taus = [p["tau"] for p in cd["blocks"][f"{view}_only"]["pairs"]]
        n = len(taus)
        return dict(mean=cd["blocks"][f"{view}_only"]["mean_tau"],
                    perfect=sum(1 for t in taus if t >= 0.999),
                    ge23=sum(1 for t in taus if t >= 2 / 3 - 1e-9),
                    le0=sum(1 for t in taus if t <= 0), n=n,
                    p=sci(ks[view]["permutation_test"]["p_value_one_sided"]))

    nv, qa = col("novelqa"), col("qasper")
    body = rf"""\begin{{table}}[h]
\centering
\begin{{tabular}}{{lrr}}
\toprule
Statistic & NovelQA & QASPER \\
\midrule
Median pairwise \(\tau_b\)               & \(2/3\) & \(2/3\) \\
Mean pairwise \(\tau_b\)                 & {nv['mean']:.3f} & {qa['mean']:.3f} \\
Permutation \(p\) value (one-sided)      & {nv['p']} & {qa['p']} \\
Pairs with perfect agreement \(\tau_b = 1\) & {nv['perfect']} / {nv['n']} & {qa['perfect']} / {qa['n']} \\
Pairs with \(\tau_b \geq 2/3\)              & {nv['ge23']} / {nv['n']} & {qa['ge23']} / {qa['n']} \\
Pairs with \(\tau_b \leq 0\) (rank-disagreement) & {nv['le0']} / {nv['n']} & {qa['le0']} / {qa['n']} \\
\bottomrule
\end{{tabular}}
\caption{{Distribution of pairwise Kendall's \(\tau_b\) across the {nv['n']} pilot
candidate-pairs on each dataset under gold scoring.
Statistics use 10{{,}}000 bootstrap resamples and permutation shuffles
with add-one smoothing~\cite{{dror2018hitchhiker}}.}}
\label{{tab:results-tau}}
\end{{table}}
"""
    write("mainstudy_tau.tex", body)


def copy_figures() -> None:
    src = MS / "figures"
    for stem in ("pareto_cost_quality", "accuracy_by_arch", "breakeven_curves", "memorization_floor", "cost_composition"):
        for ext in ("pdf", "png"):
            s = src / f"{stem}.{ext}"
            if s.exists():
                shutil.copy2(s, EXPORT / f"mainstudy_{stem}.{ext}")
        print(f"  copied figure mainstudy_{stem}.pdf/.png")


def main() -> int:
    print(f"tables + figures -> {EXPORT}")
    cost_table()
    cost_decomposition_table()
    breakeven_table()
    memorization_table()
    tau_table()
    macros()
    copy_figures()
    print(f"\nmemorization floor (for prose, not a table): nocontext "
          f"{mem['nocontext_accuracy']:.4f}, flat {mem['flat_accuracy']:.4f}, "
          f"lift {mem['lift']:+.4f}")
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
