"""Paper-ready LaTeX tables for the main study, driven entirely from the on-disk
analysis JSONs (no hardcoded metrics). Each emitted file is a complete float that
the paper imports via \\input{generated/...}; existing \\label keys are preserved
so cross-references keep resolving after the inline tables are swapped out.

Outputs into code/outputs/main_study/export/ (the staging dir promoted to
thesis-msc/generated/ by make export-assets):
  mainstudy_quality_ci.tex   -> tab:results-arch-mean   (per-arch quality + 95% CI)
  mainstudy_cost.tex         -> tab:results-cost-quality (deployment cost, both cards)
  mainstudy_breakeven.tex    -> tab:results-breakeven    (break-even N* per doc)
  mainstudy_significance.tex -> tab:results-significance (paired clustered bootstrap)
The three figure PDFs/PNGs are also copied in with stable paper names.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MS = ROOT / "outputs" / "main_study"
EXPORT = MS / "export"
EXPORT.mkdir(parents=True, exist_ok=True)

ARCHS = ["flat", "naive_rag", "raptor", "graphrag"]
LABEL = {"flat": "Flat", "naive_rag": "Naive RAG", "raptor": "RAPTOR", "graphrag": "GraphRAG"}

sig = json.loads((MS / "significance.json").read_text(encoding="utf-8"))
cost = json.loads((MS / "cost_per_arch.json").read_text(encoding="utf-8"))
brk = json.loads((MS / "breakeven.json").read_text(encoding="utf-8"))
mem = json.loads((MS / "memorization_control.json").read_text(encoding="utf-8"))

QA = sig["datasets"]["qasper"]["per_arch"]
NV = sig["datasets"]["novelqa"]["per_arch"]
PC = cost["per_arch"]


def ci(d: dict) -> str:
    return f"{d['mean']:.3f} [{d['ci_low']:.3f}, {d['ci_high']:.3f}]"


HEADER = "% Auto-generated by code/scripts/tables_main_study.py from\n" \
         "% code/outputs/main_study/{significance,cost_per_arch,breakeven,memorization_control}.json\n" \
         "% Do not edit by hand; regenerate and re-export.\n"


def write(name: str, body: str) -> None:
    (EXPORT / name).write_text(HEADER + body, encoding="utf-8")
    print(f"  wrote {name}")


def texint(n: int) -> str:
    """Integer with a LaTeX-math thousands separator, e.g. 1348 -> 1{,}348."""
    return f"{n:,}".replace(",", "{,}")


def quality_table() -> None:
    rows = "\n".join(
        f"{LABEL[a]} & {ci(QA[a])} & {ci(NV[a])} \\\\" for a in ARCHS)
    qn, qc = texint(QA["flat"]["n_questions"]), QA["flat"]["n_clusters"]
    nn, nc = texint(NV["flat"]["n_questions"]), NV["flat"]["n_clusters"]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Per-architecture answer quality on the held-out evaluation pools
($N=5$ repeats at $T=0$; QASPER ${qn}$ free-form questions over ${qc}$ papers,
NovelQA ${nn}$ multiple-choice questions over ${nc}$ novels,
the five calibration novels excluded).
Cells report the mean with a $95\%$ confidence interval from a paired
clustered bootstrap ($10{{,}}000$ resamples; clusters are papers for QASPER and
novels for NovelQA). QASPER is scored with the official Answer-F1 metric;
NovelQA with held-out Codabench accuracy. The ranking
Flat $>$ Naive RAG $\gtrsim$ RAPTOR $>$ GraphRAG is identical on both
datasets; there is no cross-dataset inversion.}}\label{{tab:results-arch-mean}}
\begin{{tabular}}{{lcc}}
\toprule
Architecture & QASPER Answer-F1 [95\% CI] & NovelQA accuracy [95\% CI] \\
\midrule
{rows}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_quality_ci.tex", body)


def cost_table() -> None:
    # order by base-card deployment total (ascending): naive, raptor, flat, graphrag
    order = sorted(ARCHS, key=lambda a: PC[f"base|{a}"]["total"])
    rows = []
    for a in order:
        b = PC[f"base|{a}"]
        c = PC[f"cache|{a}"]
        rows.append(
            f"{LABEL[a]} & {b['c_off_total']:.2f} & {b['c_on_total']:.2f} & "
            f"{b['total']:.2f} & {c['total']:.2f} & {b['c_on_per_query']*1000:.2f} \\\\")
    rows_tex = "\n".join(rows)
    base_tot = cost["deployment_total"]["base"]
    cache_tot = cost["deployment_total"]["cache"]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Per-architecture deployment cost in USD on the primary answerer
(\texttt{{gemini-3.1-flash-lite-preview}}), run-index-0 over the full answered grid.
$C_{{\text{{off}}}}$ is
the one-time index/build cost; $C_{{\text{{on}}}}$ is the total per-query
answering cost. ``Deploy'' totals are reported
under both the standard and the cache-discount price cards; the rightmost column
is the marginal per-query cost in milli-dollars. Embedding compute is billed at
the local GPU rate. The cost ranking (Naive RAG $<$ RAPTOR $<$ Flat $<$ GraphRAG)
is orthogonal to the quality ranking, which is what the Pareto analysis
(Figure~\ref{{fig:pareto-cost-quality}}) resolves. Grid totals:
\${base_tot:.2f} (standard) / \${cache_tot:.2f} (cache-discount).}}\label{{tab:results-cost-quality}}
\begin{{tabular}}{{lrrrrr}}
\toprule
 & $C_{{\text{{off}}}}$ & $C_{{\text{{on}}}}$ & Deploy & Deploy & $C_{{\text{{on}}}}$/query \\
Architecture & (USD) & (USD) & std (USD) & cache (USD) & (m\$) \\
\midrule
{rows_tex}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_cost.tex", body)


def breakeven_table() -> None:
    flat_q = PC["base|flat"]["c_on_per_query"]
    rows = []
    for a in ("naive_rag", "raptor", "graphrag"):
        bb = brk[f"base|{a}"]
        bc = brk[f"cache|{a}"]
        nb = bb["n_star"]
        nc = bc["n_star"]
        nb_s = "any $N\\ge1$" if nb is not None and nb < 1 else (f"{nb:.1f}" if nb else "---")
        nc_s = "any $N\\ge1$" if nc is not None and nc < 1 else (f"{nc:.1f}" if nc else "---")
        rows.append(
            f"{LABEL[a]} & {bb['c_off_per_doc']*1000:.2f} & {bb['c_on_per_query']*1000:.3f} "
            f"& {nb_s} & {nc_s} \\\\")
    rows_tex = "\n".join(rows)
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Break-even query density versus cache-aware Flat. A structured
architecture amortizes its per-document build cost $C_{{\text{{off}}}}/\text{{doc}}$
over $N$ queries; $N^\star$ is the questions-per-document density at which its
amortized cost per query falls below Flat's marginal
\${flat_q*1000:.2f} per query. Reported under both price cards. Naive RAG is
cheaper than Flat at any realistic density; RAPTOR and GraphRAG only repay their
build cost above $N^\star$, beyond the realistic operating density of both
workloads (QASPER $\approx4$ q/paper, NovelQA $\approx25$ q/novel)---and even
there they answer no better than Naive RAG.}}\label{{tab:results-breakeven}}
\begin{{tabular}}{{lrrcc}}
\toprule
 & $C_{{\text{{off}}}}$/doc & $C_{{\text{{on}}}}$/query & $N^\star$ & $N^\star$ \\
Architecture & (m\$) & (m\$) & std & cache \\
\midrule
{rows_tex}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_breakeven.tex", body)


def significance_table() -> None:
    def block(ds_key: str, ds_name: str) -> str:
        pw = sig["datasets"][ds_key]["pairwise"]
        out = [f"\\multicolumn{{4}}{{l}}{{\\textit{{{ds_name}}}}} \\\\"]
        for p in pw:
            star = "yes" if p["significant"] else "no"
            out.append(
                f"{LABEL[p['a']]} vs {LABEL[p['b']]} & {p['mean_diff']:+.3f} & "
                f"[{p['ci_low']:+.3f}, {p['ci_high']:+.3f}] & {star} \\\\")
        return "\n".join(out)
    nr = next(p for p in sig["datasets"]["novelqa"]["pairwise"]
              if {p["a"], p["b"]} == {"naive_rag", "raptor"})
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Paired clustered-bootstrap significance ($10{{,}}000$ resamples,
percentile $95\%$ CI on the mean difference; clusters are papers for QASPER and
novels for NovelQA). Every QASPER pair is significant. On NovelQA every pair is
significant except Naive RAG versus RAPTOR (${nr['mean_diff']:+.3f}$, CI straddles zero),
which are statistically tied.}}\label{{tab:results-significance}}
\begin{{tabular}}{{lrcc}}
\toprule
Pair & $\Delta$ mean & 95\% CI of $\Delta$ & Significant \\
\midrule
{block("qasper", "QASPER (Answer-F1)")}
\midrule
{block("novelqa", "NovelQA (accuracy)")}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_significance.tex", body)


def memorization_table() -> None:
    """Closed-book (no-document) control vs flat full-context, both datasets."""
    q = mem.get("qasper", {})
    nv_floor, nv_flat = mem["nocontext_accuracy"], mem["flat_accuracy"]
    qa_floor, qa_flat = q.get("nocontext_answer_f1"), q.get("flat_answer_f1")
    rows = [
        f"NovelQA & Accuracy & {nv_floor:.2f} & {nv_flat:.2f} & {nv_flat - nv_floor:+.2f} \\\\",
        f"QASPER & Answer-F1 & {qa_floor:.2f} & {qa_flat:.2f} & {qa_flat - qa_floor:+.2f} \\\\",
    ]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Memorization control: closed-book (question, and options for NovelQA,
with the document \emph{{withheld}}) versus flat full-context. NovelQA's
public-domain novels are recalled well above the $0.25$ four-way-MC chance rate,
so its absolute accuracies are memorization-inflated; QASPER's research papers
are not recalled (closed-book Answer-F1 near zero), so its scores reflect genuine
reading. The architecture ranking is identical on both, so the comparison is not
confounded by memorization even though the NovelQA absolute level is.}}\label{{tab:results-memorization}}
\begin{{tabular}}{{llccc}}
\toprule
Dataset & Metric & Closed-book & Flat (with doc.) & Reading lift \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_memorization.tex", body)


def copy_figures() -> None:
    src = MS / "figures"
    for stem in ("pareto_cost_quality", "accuracy_by_arch", "breakeven_curves"):
        for ext in ("pdf", "png"):
            s = src / f"{stem}.{ext}"
            if s.exists():
                shutil.copy2(s, EXPORT / f"mainstudy_{stem}.{ext}")
        print(f"  copied figure mainstudy_{stem}.pdf/.png")


def main() -> int:
    print(f"tables + figures -> {EXPORT}")
    quality_table()
    cost_table()
    breakeven_table()
    significance_table()
    memorization_table()
    copy_figures()
    print(f"\nmemorization floor (for prose, not a table): nocontext "
          f"{mem['nocontext_accuracy']:.4f}, flat {mem['flat_accuracy']:.4f}, "
          f"lift {mem['lift']:+.4f}")
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
