"""Paper-ready LaTeX tables for the main study, driven entirely from the on-disk
analysis JSONs (no hardcoded metrics). Each emitted file is a complete float that
the paper imports via \\input{generated/...}; existing \\label keys are preserved
so cross-references keep resolving after the inline tables are swapped out.

Outputs into code/outputs/main_study/export/ (the staging dir promoted to
thesis-msc/generated/ by make export-assets):
  mainstudy_cost.tex         -> tab:results-cost-quality (deployment cost, both cards)
  mainstudy_cost_decomposition.tex -> tab:results-cost-decomp (build/answer x LLM/embed)
  mainstudy_breakeven.tex    -> tab:results-breakeven    (break-even N* per doc)
  mainstudy_significance.tex -> tab:results-significance (paired clustered bootstrap)
The three figure PDFs/PNGs are also copied in with stable paper names.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MS = ROOT / "outputs" / "main_study"
EXPORT = MS / "export"
EXPORT.mkdir(parents=True, exist_ok=True)

ARCHS = ["flat", "naive_rag", "raptor", "graphrag"]
LABEL = {"flat": "Flat", "naive_rag": "Naive RAG", "raptor": "RAPTOR", "graphrag": "GraphRAG"}

sig = json.loads((MS / "significance.json").read_text(encoding="utf-8"))
cost = json.loads((MS / "cost_per_arch.json").read_text(encoding="utf-8"))
brk = json.loads((MS / "breakeven.json").read_text(encoding="utf-8"))
brk_ds = json.loads((MS / "breakeven_by_dataset.json").read_text(encoding="utf-8"))
costds = json.loads((MS / "cost_by_dataset.json").read_text(encoding="utf-8"))
mem = json.loads((MS / "memorization_control.json").read_text(encoding="utf-8"))

QA = sig["datasets"]["qasper"]["per_arch"]
NV = sig["datasets"]["novelqa"]["per_arch"]
PC = cost["per_arch"]


def ci(d: dict) -> str:
    return f"{d['mean']:.3f} [{d['ci_low']:.3f}, {d['ci_high']:.3f}]"


HEADER = "% Auto-generated by code/scripts/tables_main_study.py from\n" \
         "% code/outputs/main_study/{significance,cost_per_arch,cost_by_dataset,breakeven,breakeven_by_dataset,memorization_control}.json\n" \
         "% Do not edit by hand; regenerate and re-export.\n"


def write(name: str, body: str) -> None:
    (EXPORT / name).write_text(HEADER + body, encoding="utf-8")
    print(f"  wrote {name}")


def texint(n: int) -> str:
    """Integer with a LaTeX-math thousands separator, e.g. 1348 -> 1{,}348."""
    return f"{n:,}".replace(",", "{,}")


def cost_table() -> None:
    def rows(ds):
        order = sorted(ARCHS, key=lambda a: costds[f"base|{a}|{ds}"]["total"])
        out = []
        for a in order:
            c = costds[f"base|{a}|{ds}"]
            out.append(f"{LABEL[a]} & {c['c_off_total']:.2f} & {c['c_on_total']:.2f} & "
                       f"{c['total']:.2f} & {c['c_on_per_query']*1000:.2f} \\\\")
        return "\n".join(out)

    qd = brk_ds["base|raptor|qasper"]["density"]
    nd = brk_ds["base|raptor|novelqa"]["density"]
    base_tot = cost["deployment_total"]["base"]
    cache_tot = cost["deployment_total"]["cache"]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Per-architecture deployment cost in USD, computed \emph{{within each workload}}
(standard price card): $C_{{\text{{off}}}}$ the one-time build, $C_{{\text{{on}}}}$ the total
answering cost, Deploy their sum, and the last column the marginal per-query cost
(m\$, $10^{{-3}}$~USD). Naive RAG is cheapest and GraphRAG dearest on both, while
\emph{{Flat and RAPTOR swap}} between the short papers and the long novels
(Section~\ref{{sec:results-cost}}). Study-wide deployment total: \${base_tot:.2f}
(standard card) / \${cache_tot:.2f} (deep-cache card, which lowers only Flat's
re-reads).}}\label{{tab:results-cost-quality}}
\begin{{tabular}}{{lrrrr}}
\toprule
 & $C_{{\text{{off}}}}$ & $C_{{\text{{on}}}}$ & Deploy & $C_{{\text{{on}}}}$/query \\
Architecture & (USD) & (USD) & (USD) & (m\$) \\
\midrule
\multicolumn{{5}}{{l}}{{\textit{{QASPER}} ($\approx{qd:.0f}$ q/paper)}} \\
{rows('qasper')}
\midrule
\multicolumn{{5}}{{l}}{{\textit{{NovelQA}} ($\approx{nd:.0f}$ q/novel)}} \\
{rows('novelqa')}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_cost.tex", body)


def cost_decomposition_table() -> None:
    # Where each architecture's deployment dollars actually go: the one-time build
    # vs the per-query answering, each split into LLM API calls and local bge-m3
    # embedding. Standard card; a study-wide roll-up (summed over both workloads ---
    # the per-workload split is in cost_table). Driven from cost_per_arch.json.
    order = sorted(ARCHS, key=lambda a: PC[f"base|{a}"]["total"])
    rows = []
    for a in order:
        b = PC[f"base|{a}"]
        rows.append(
            f"{LABEL[a]} & {b['gemini_off']:.2f} & {b['embed_off']:.2f} & "
            f"{b['gemini_on']:.2f} & {b['embed_on']:.2f} & {b['total']:.2f} & "
            f"{b['c_store_total']:.3f} \\\\")
    rows_tex = "\n".join(rows)
    gr, rp = PC["base|graphrag"], PC["base|raptor"]
    f_base, f_cache = PC["base|flat"]["total"], PC["cache|flat"]["total"]
    # Deep-cache prices cached input at 0.1x uncached vs the standard card's 0.25x
    # (a 0.4x factor), so the standard->deep saving is 0.6x of the cached re-read
    # cost; invert it to recover the cached re-reads under the standard card and
    # the undiscounted remainder (uncached first read + output).
    cached_base = (f_base - f_cache) / 0.6
    other = f_base - cached_base
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Where each architecture's deployment dollars go, summed over the whole study
(standard card; the per-workload split is Table~\ref{{tab:results-cost-quality}}): the one-time
build ($C_{{\text{{off}}}}$) and the per-query answering ($C_{{\text{{on}}}}$), each split
into LLM API calls and local \texttt{{bge-m3}} embedding. Persistent-artifact storage
($C_{{\text{{store}}}}$) is shown separately---it folds into the study-wide amortized
cost, not the deployment total. All values in USD. Build cost is dominated by LLM
calls: GraphRAG's entity and community extraction (\${gr['gemini_off']:.2f}) and
RAPTOR's tree summarization (\${rp['gemini_off']:.2f}); embedding is a minor line
except RAPTOR's per-node tree vectors (\${rp['embed_off']:.2f}). Flat carries no
build and no embedding---its \${f_base:.2f} is entirely answering API, of which about
\${cached_base:.2f} is the cached re-reads the deep-cache card reprices and
\${other:.2f} is the uncached first read of each document plus all output, which no
cache discount touches.}}\label{{tab:results-cost-decomp}}
\begin{{tabular}}{{lrrrrrr}}
\toprule
 & \multicolumn{{2}}{{c}}{{Build ($C_{{\text{{off}}}}$)}} & \multicolumn{{2}}{{c}}{{Answer ($C_{{\text{{on}}}}$)}} & & \\
\cmidrule(lr){{2-3}}\cmidrule(lr){{4-5}}
Architecture & LLM & embed & LLM & embed & Deploy & Storage \\
 & (USD) & (USD) & (USD) & (USD) & (USD) & (USD) \\
\midrule
{rows_tex}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_cost_decomposition.tex", body)


def breakeven_table() -> None:
    def fmt_nstar(b):
        n = b["n_star"]
        if n is None:
            return "never"
        return "any $N\\ge1$" if n < 1 else f"{n:.1f}"

    def rows(ds):
        out = []
        for a in ("naive_rag", "raptor", "graphrag"):
            bb, bc = brk_ds[f"base|{a}|{ds}"], brk_ds[f"cache|{a}|{ds}"]
            out.append(f"{LABEL[a]} & {bb['c_off_per_doc']*1000:.2f} & {bb['c_on_per_query']*1000:.3f} "
                       f"& {fmt_nstar(bb)} & {fmt_nstar(bc)} \\\\")
        return "\n".join(out)

    def flatq(ds, card):
        return brk_ds[f"{card}|raptor|{ds}"]["flat_c_on_per_query"] * 1000

    qd = brk_ds["base|raptor|qasper"]["density"]
    nd = brk_ds["base|raptor|novelqa"]["density"]
    qr = brk_ds["base|raptor|qasper"]["n_star"]
    nr = brk_ds["base|raptor|novelqa"]["n_star"]
    ng = brk_ds["base|graphrag|novelqa"]["n_star"]
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Break-even query density versus cache-aware Flat, computed \emph{{within each
workload}}: the per-document build cost and Flat's per-query cost both scale with document
length, so a single pooled threshold describes neither. A structured architecture amortizes
its per-document build $C_{{\text{{off}}}}/\text{{doc}}$ over $N$ queries; $N^\star$ is the
questions-per-document density at which its amortized cost per query drops below Flat's
marginal. Naive RAG is cheaper than Flat at any density on both workloads. On QASPER
($\approx{qd:.0f}$ q/paper) neither structured method repays: RAPTOR needs
$N^\star\approx{qr:.0f}$, above the density, and GraphRAG \emph{{never}} breaks even because
its per-query cost already exceeds Flat's re-read of the short paper. On NovelQA
($\approx{nd:.0f}$ q/novel) RAPTOR repays under the standard card ($N^\star\approx{nr:.0f}$)
but not under the cache-discount card, while GraphRAG needs $\approx{ng:.0f}$ q/novel, far
above the workload. Even where a build is recovered the method answers no better than Flat and
Naive RAG stays cheaper, so break-even never becomes a quality or cost-position
advantage.}}\label{{tab:results-breakeven}}
\begin{{tabular}}{{lrrcc}}
\toprule
 & $C_{{\text{{off}}}}$/doc & $C_{{\text{{on}}}}$/query & $N^\star$ & $N^\star$ \\
Architecture & (m\$) & (m\$) & std & cache \\
\midrule
\multicolumn{{5}}{{l}}{{\textit{{QASPER}} ($\approx{qd:.0f}$ q/paper; Flat {flatq('qasper','base'):.2f}/{flatq('qasper','cache'):.2f}~m\$/q std/cache)}} \\
{rows('qasper')}
\midrule
\multicolumn{{5}}{{l}}{{\textit{{NovelQA}} ($\approx{nd:.0f}$ q/novel; Flat {flatq('novelqa','base'):.2f}/{flatq('novelqa','cache'):.2f}~m\$/q std/cache)}} \\
{rows('novelqa')}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_breakeven.tex", body)


def significance_table() -> None:
    def block(ds_key: str, ds_name: str) -> str:
        pw = sig["datasets"][ds_key]["pairwise"]
        out = [f"\\multicolumn{{5}}{{l}}{{\\textit{{{ds_name}}}}} \\\\"]
        for p in pw:
            star = "yes" if p["significant"] else "no"
            pv = p["p_value"]
            p_str = "$<0.001$" if pv < 0.001 else f"{pv:.3f}"
            out.append(
                f"{LABEL[p['a']]} vs {LABEL[p['b']]} & {p['mean_diff']:+.3f} & "
                f"[{p['ci_low']:+.3f}, {p['ci_high']:+.3f}] & {p_str} & {star} \\\\")
        return "\n".join(out)
    nr = next(p for p in sig["datasets"]["novelqa"]["pairwise"]
              if {p["a"], p["b"]} == {"naive_rag", "raptor"})
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Paired clustered-bootstrap significance ($10{{,}}000$ resamples,
percentile $95\%$ CI on the mean difference and the two-sided bootstrap $p$-value ($p<0.05$ counts as significant); clusters are papers for QASPER and
novels for NovelQA). Every QASPER pair is significant. On NovelQA every pair is
significant except Naive RAG versus RAPTOR (${nr['mean_diff']:+.3f}$, CI straddles zero),
which are statistically tied.}}\label{{tab:results-significance}}
\begin{{tabular}}{{lrccc}}
\toprule
Pair & $\Delta$ mean & 95\% CI of $\Delta$ & $p$ & Significant \\
\midrule
{block("qasper", "QASPER (Answer-F1)")}
\midrule
{block("novelqa", "NovelQA (accuracy)")}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_significance.tex", body)


def memorization_table() -> None:
    """Per-architecture quality vs the closed-book floor, both datasets."""
    nv, qa = mem["novelqa"], mem["qasper"]
    nv_floor, qa_floor = nv["closed_book"], qa["closed_book"]
    rows = [f"Closed-book floor & {qa_floor:.2f} & --- & {nv_floor:.2f} & --- \\\\", r"\midrule"]
    for a in ARCHS:
        n, q = nv["per_arch"][a], qa["per_arch"][a]
        rows.append(f"{LABEL[a]} & {q['answer_f1']:.2f} & {q['lift']:+.2f} & "
                    f"{n['accuracy']:.2f} & {n['lift']:+.2f} \\\\")
    rows_tex = "\n".join(rows)
    body = rf"""\begin{{table}}[ht]
\centering
\caption{{Memorization control: per-architecture answer quality against the
closed-book floor (the document \emph{{withheld}}; question, and options for NovelQA).
NovelQA's public-domain classics are recalled well above the $0.25$ four-way-MC
chance rate---closed-book accuracy is already {nv_floor:.2f}---so its absolute
scores are memorization-inflated, whereas QASPER's research papers are not recalled
(closed-book Answer-F1 {qa_floor:.2f}) and require the document. The reading lift
(with-document minus closed-book) measures the usable evidence each architecture
supplies: Flat lifts NovelQA accuracy by ${nv['per_arch']['flat']['lift']:+.2f}$,
whereas GraphRAG adds almost nothing (${nv['per_arch']['graphrag']['lift']:+.2f}$)
over closed-book guessing. The architecture ranking is the same with and without
the memorization caveat, so the comparison is not confounded by memorization
even though the NovelQA absolute level is.}}\label{{tab:results-memorization}}
\begin{{tabular}}{{lcccc}}
\toprule
 & \multicolumn{{2}}{{c}}{{QASPER Answer-F1}} & \multicolumn{{2}}{{c}}{{NovelQA accuracy}} \\
Architecture & with doc. & lift & with doc. & lift \\
\midrule
{rows_tex}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("mainstudy_memorization.tex", body)


def macros() -> None:
    """Inline result numbers as \\input-able \\newcommand macros, so values can stay in
    the prose while still living in exactly one regenerated place (no hand-typed metrics).
    Driven from the same JSONs as the tables. LaTeX control sequences are letters-only,
    so e.g. Answer-F1 -> \\qFlatFone."""
    def fp(ds: str, a: str, b: str) -> dict:
        return next(p for p in sig["datasets"][ds]["pairwise"]
                    if {p["a"], p["b"]} == {a, b})
    fn = fp("qasper", "flat", "naive_rag")
    nr = fp("novelqa", "naive_rag", "raptor")
    m = [
        f"\\newcommand{{\\qFlatFone}}{{{QA['flat']['mean']:.3f}}}",
        f"\\newcommand{{\\qNaiveFone}}{{{QA['naive_rag']['mean']:.3f}}}",
        f"\\newcommand{{\\qRaptorFone}}{{{QA['raptor']['mean']:.3f}}}",
        f"\\newcommand{{\\qGraphFone}}{{{QA['graphrag']['mean']:.3f}}}",
        f"\\newcommand{{\\nFlatAcc}}{{{NV['flat']['mean']:.3f}}}",
        f"\\newcommand{{\\nNaiveAcc}}{{{NV['naive_rag']['mean']:.3f}}}",
        f"\\newcommand{{\\nRaptorAcc}}{{{NV['raptor']['mean']:.3f}}}",
        f"\\newcommand{{\\nGraphAcc}}{{{NV['graphrag']['mean']:.3f}}}",
        f"\\newcommand{{\\deltaFlatNaiveQ}}{{{fn['mean_diff']:.3f}}}",
        f"\\newcommand{{\\pFlatNaiveQ}}{{{fn['p_value']:.3f}}}",
        f"\\newcommand{{\\deltaNaiveRaptorN}}{{{nr['mean_diff']:.3f}}}",
        f"\\newcommand{{\\costFlatQ}}{{{costds['base|flat|qasper']['total']:.2f}}}",
        f"\\newcommand{{\\costRaptorQ}}{{{costds['base|raptor|qasper']['total']:.2f}}}",
        f"\\newcommand{{\\costFlatN}}{{{costds['base|flat|novelqa']['total']:.2f}}}",
        f"\\newcommand{{\\costRaptorN}}{{{costds['base|raptor|novelqa']['total']:.2f}}}",
        f"\\newcommand{{\\nstarRaptorQ}}{{{round(brk_ds['base|raptor|qasper']['n_star'])}}}",
        f"\\newcommand{{\\nstarRaptorN}}{{{round(brk_ds['base|raptor|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\nstarRaptorNcache}}{{{round(brk_ds['cache|raptor|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\nstarGraphN}}{{{round(brk_ds['base|graphrag|novelqa']['n_star'])}}}",
        f"\\newcommand{{\\densQasper}}{{{round(brk_ds['base|raptor|qasper']['density'])}}}",
        f"\\newcommand{{\\densNovel}}{{{round(brk_ds['base|raptor|novelqa']['density'])}}}",
        f"\\newcommand{{\\memQasperFloor}}{{{mem['qasper']['closed_book']:.2f}}}",
        f"\\newcommand{{\\memNovelFloor}}{{{mem['novelqa']['closed_book']:.2f}}}",
        f"\\newcommand{{\\memFlatLiftN}}{{{mem['novelqa']['per_arch']['flat']['lift']:+.2f}}}",
        f"\\newcommand{{\\memGraphLiftN}}{{{mem['novelqa']['per_arch']['graphrag']['lift']:+.2f}}}",
        f"\\newcommand{{\\billedGemini}}{{{cost['billed_gemini']:.2f}}}",
        f"\\newcommand{{\\nNovelScored}}{{{texint(NV['flat']['n_questions'])}}}",
        f"\\newcommand{{\\nNovelDocs}}{{{NV['flat']['n_clusters']}}}",
        f"\\newcommand{{\\nQasperQ}}{{{texint(QA['flat']['n_questions'])}}}",
        f"\\newcommand{{\\nQasperDocs}}{{{QA['flat']['n_clusters']}}}",
        f"\\newcommand{{\\nTotalQ}}{{{texint(QA['flat']['n_questions'] + NV['flat']['n_questions'])}}}",
    ]
    write("mainstudy_macros.tex", "\n".join(m) + "\n")


def tau_table() -> None:
    """Pilot rank-stability distribution table (tab:results-tau), generated from the
    under-gold cross-dataset pairwise blocks and the permutation-test stats, so the lone
    remaining hand-typed results table joins the generated-asset pipeline."""
    SAN = ROOT / "outputs" / "sanity"
    cd = json.loads((SAN / "kendall_cross_dataset_under_gold_20260520.json").read_text(encoding="utf-8"))
    ks = json.loads((SAN / "kendall_stats_20260520.json").read_text(encoding="utf-8"))["results"]

    def sci(p: float) -> str:
        from math import log10, floor
        e = floor(log10(p))
        m = round(p / 10 ** e)
        return f"\\({m}\\!\\times\\!10^{{{e}}}\\)"

    def col(view: str) -> dict:
        taus = [p["tau"] for p in cd["blocks"][f"{view}_only"]["pairs"]]
        n = len(taus)
        return dict(mean=cd["blocks"][f"{view}_only"]["mean_tau"],
                    perfect=sum(1 for t in taus if t >= 0.999),
                    le0=sum(1 for t in taus if t <= 0), n=n,
                    p=sci(ks[view]["permutation_test"]["p_value_one_sided"]))

    nv, qa = col("novelqa"), col("qasper")
    body = rf"""\begin{{table}}[h]
\centering
\begin{{tabular}}{{lrr}}
\toprule
Statistic & NovelQA & QASPER \\
\midrule
Median pairwise \(\tau_b\)               & \(2/3\) & \(2/3\) \\
Mean pairwise \(\tau_b\)                 & {nv['mean']:.3f} & {qa['mean']:.3f} \\
Permutation \(p\) value (one-sided)      & {nv['p']} & {qa['p']} \\
Pairs with perfect agreement \(\tau_b = 1\) & {nv['perfect']} / {nv['n']} & {qa['perfect']} / {qa['n']} \\
Pairs with \(\tau_b \leq 0\) (rank-disagreement) & {nv['le0']} / {nv['n']} & {qa['le0']} / {qa['n']} \\
\bottomrule
\end{{tabular}}
\caption{{Distribution of pairwise Kendall \(\tau_b\) across the {nv['n']} pilot
candidate-pairs on each dataset under gold scoring.
Statistics use 10{{,}}000 bootstrap resamples and permutation shuffles
with add-one smoothing~\cite{{dror2018hitchhiker}}.
The within-dataset medians justified the single-answerer main study;
they are a pilot diagnostic, superseded by the main study's clustered
bootstrap (Figure~\ref{{fig:per-arch-accuracy}}).}}
\label{{tab:results-tau}}
\end{{table}}
"""
    write("mainstudy_tau.tex", body)


def copy_figures() -> None:
    src = MS / "figures"
    for stem in ("pareto_cost_quality", "accuracy_by_arch", "breakeven_curves", "memorization_floor", "cost_composition"):
        for ext in ("pdf", "png"):
            s = src / f"{stem}.{ext}"
            if s.exists():
                shutil.copy2(s, EXPORT / f"mainstudy_{stem}.{ext}")
        print(f"  copied figure mainstudy_{stem}.pdf/.png")


def main() -> int:
    print(f"tables + figures -> {EXPORT}")
    cost_table()
    cost_decomposition_table()
    breakeven_table()
    significance_table()
    memorization_table()
    tau_table()
    macros()
    copy_figures()
    print(f"\nmemorization floor (for prose, not a table): nocontext "
          f"{mem['nocontext_accuracy']:.4f}, flat {mem['flat_accuracy']:.4f}, "
          f"lift {mem['lift']:+.4f}")
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
